name: Build ModemManager for BCM2711
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWRT
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git libelf-dev libncurses-dev libssl-dev python3 python3-pip \
            zlib1g-dev libdeflate-dev gzip rsync unzip wget
          pip3 install netifaces

      - name: Fix Lua Extraction (Workaround)
        run: |
          # Force use of system gzip instead of libdeflate-gzip
          mkdir -p staging_dir/host/bin
          ln -s /bin/gzip staging_dir/host/bin/libdeflate-gzip

      - name: Configure OpenWRT
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "CONFIG_TARGET_bcm27xx=y" >> .config
          echo "CONFIG_TARGET_bcm27xx_bcm2711=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager=y" >> .config
          echo "CONFIG_PACKAGE_modemmanager-rpcd=y" >> .config
          echo "CONFIG_PACKAGE_libqmi=y" >> .config
          echo "CONFIG_PACKAGE_libmbim=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-modemmanager=y" >> .config
          make defconfig

      - name: Compile (Debug Mode)
        run: |
          make -j1 V=s package/utils/lua/host/compile || make -j1 V=s package/utils/lua/host/compile  # Build Lua first
          make -j$(nproc) package/libqmi/compile
          make -j$(nproc) package/libmbim/compile
          make -j$(nproc) package/modemmanager/compile
          make -j$(nproc) package/modemmanager-rpcd/compile
          make -j$(nproc) package/luci-proto-modemmanager/compile

      - name: Upload IPKs
        uses: actions/upload-artifact@v4
        with:
          name: modemmanager-ipks
          path: bin/packages/*/base/*.ipk
